language: go

services:
  - postgresql

go:
  - 1.9
  - tip

env:
  global:
    - DB_NAME=opencrypter
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_HOST=127.0.0.1
    - GIN_MODE=debug

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only
  - go get github.com/golang/mock/mockgen
  - mkdir mock
  - mockgen -source=domain/device.go -destination mock/device_mock.go -package mock
  - mockgen -source=domain/account.go -destination mock/account_mock.go -package mock
  - go get -t -v ./...

before_script:
  - psql -c 'create database opencrypter;' -U postgres

script:
  - go test ./... -covermode=atomic -race -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0c8ffc90bfa497096187
    on_success: always
    on_failure: always
    on_start: never
